# REQUIRED
# Path to a tab separated samplesheet that contains a header
# 'sample\tR1\tR2
samples:


# REQUIRED
# Specify one, or both assemblers to use.
assembly:
    - metaspades
    - megahit

# Interval in seconds to query running processes
# Defaults to 300 (every 5 min)
ps_interval: 60

# REQUIRED
# Path to CAT db and CAT taxonomy, as output from CAT prepare
# see https://github.com/dutilh/CAT#downloading-the-database-files
CAT_DB: 
CAT_TAX: 

# REQUIRED
# Specify a working copy of the CAT executable with the reads module available. 
# Until this is packaged with CAT this is required.
# After that, it should come with the cat.yaml environment.
CAT_DEV:
